### ISSUE TITLE
django error:

### ISSUE THREAD

**Issue by mohit888** [mohit888/django-error#1]
### **INPUT:-**
from django.db import models

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
         return self.top_name
class webpage(models.Model):
    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=264,unique = True)
    url = models.URLField(unique = True)

    def __str__(self):
         return self.name

class AcessRecord(models.Model):
    name = models.ForeignKey(webpage)
    date = models.DateField()

    def __str__(self):
         return str(self.date)

### **OUTPUT:-**

populating script
Traceback (most recent call last):
  File "populate_dimag.py", line 34, in <module>
    populate(20)
  File "populate_dimag.py", line 29, in populate
    webpg = webpage.objects.get_or_create(topic=top,url=fake_url,date=fake_date,name=fake_name)[0]
  File "C:\Users\mohit\Anaconda3\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\django\db\models\query.py", line 459, in get_or_create
    lookup, params = self._extract_model_params(defaults, **kwargs)
  File "C:\Users\mohit\Anaconda3\lib\site-packages\django\db\models\query.py", line 534, in _extract_model_params
    "', '".join(sorted(invalid_params)),
django.core.exceptions.FieldError: Invalid field name(s) for model webpage: 'date'.

**Comment by mohit888** [comment]
i found the solution
